#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PROG=/usr/libexec/tgpasswall/bot.sh
CFG=main

start_service() {
	enabled="$(uci -q get tgpasswall.${CFG}.enabled)"
	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param env TG_CONFIG_SECTION="$CFG"
	procd_close_instance
}

reload_service() {
	stop
	start
}
